Default: &defaults
  database: HaskellPie.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: HaskellPie_test.sqlite3
  <<: *defaults

Staging:
  database: HaskellPie_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: HaskellPie_production.sqlite3
  poolsize: 100
  <<: *defaults
